In [1]:
from g5nr import G5NR_QC, Meta, Target, Features
import pandas as pd

import sys
sys.path.append('..')
    
    
pd.set_option('display.float_format', lambda x: '%.2f' % x)

x = G5NR_QC(Dir='..')

any valid? True

In [2]:
print("Angles")
x.toDataFrame(Vars=['GlintAngle', 'ScatteringAngle']).describe()

Angles

,GlintAngle.01,GlintAngle.02,GlintAngle.03,GlintAngle.04,GlintAngle.05,GlintAngle.06,GlintAngle.07,GlintAngle.08,GlintAngle.09,GlintAngle.10,ScatteringAngle.01,ScatteringAngle.02,ScatteringAngle.03,ScatteringAngle.04,ScatteringAngle.05,ScatteringAngle.06,ScatteringAngle.07,ScatteringAngle.08,ScatteringAngle.09,ScatteringAngle.10
count,119319.00,119319.00,119319.00,119319.00,119319.00,119319.00,119319.00,119319.00,119319.00,119319.00,119319.00,119319.00,119319.00,119319.00,119319.00,119319.00,119319.00,119319.00,119319.00,119319.00
mean,71.54,61.88,54.98,50.30,47.73,47.24,48.88,52.78,59.13,68.53,111.43,120.78,127.12,131.04,132.74,132.30,129.77,125.16,118.33,108.70
std,36.19,31.54,26.20,21.12,17.85,18.08,21.67,26.92,32.31,36.81,36.75,32.22,26.86,21.64,18.06,17.88,21.16,26.21,31.54,36.18
min,18.92,19.73,20.06,19.95,19.44,18.62,17.70,16.84,16.33,16.24,40.47,54.42,67.69,80.71,93.67,93.70,80.69,67.59,54.23,40.11
25%,36.28,33.08,32.96,32.49,31.81,31.09,30.44,30.02,29.95,32.39,79.16,93.02,105.73,117.80,117.86,117.59,116.40,103.90,90.85,76.65
50%,68.42,54.79,46.37,46.13,45.63,45.21,44.75,44.39,51.00,64.48,115.50,128.92,135.51,135.17,134.75,134.38,133.94,133.74,125.47,111.90
75%,103.62,89.36,76.23,63.63,62.43,62.13,62.15,74.22,86.97,100.85,147.54,149.90,149.81,149.42,148.86,148.23,147.66,147.22,147.13,144.02
max,140.15,125.96,112.51,99.32,86.29,86.35,99.27,112.37,125.70,139.70,163.46,163.36,162.86,162.18,161.38,160.67,160.18,160.06,160.36,161.04

In [3]:
x.toDataFrame(Vars=Features).describe()

,Ref360.01,Ref360.02,Ref360.03,Ref360.04,Ref360.05,Ref360.06,Ref360.07,Ref360.08,Ref360.09,Ref360.10,...,Sre1650.01,Sre1650.02,Sre1650.03,Sre1650.04,Sre1650.05,Sre1650.06,Sre1650.07,Sre1650.08,Sre1650.09,Sre1650.10
count,119319.00,119319.00,119319.00,119319.00,119319.00,119319.00,119319.00,119319.00,119319.00,119319.00,...,119319.00,119319.00,119319.00,119319.00,119319.00,119319.00,119319.00,119319.00,119319.00,119319.00
mean,0.44,0.34,0.28,0.25,0.24,0.24,0.25,0.28,0.33,0.44,...,0.05,0.06,0.05,0.06,0.06,0.06,0.06,0.07,0.07,0.07
std,0.18,0.11,0.08,0.05,0.04,0.05,0.06,0.08,0.12,0.18,...,0.11,0.11,0.11,0.11,0.11,0.12,0.12,0.12,0.12,0.13
min,0.15,0.12,0.11,0.12,0.12,0.13,0.12,0.12,0.13,0.16,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
25%,0.29,0.24,0.22,0.22,0.22,0.22,0.21,0.22,0.24,0.29,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
50%,0.38,0.30,0.26,0.24,0.23,0.23,0.23,0.25,0.30,0.37,...,0.00,0.00,0.00,0.00,0.01,0.01,0.01,0.02,0.02,0.01
75%,0.56,0.41,0.33,0.28,0.25,0.25,0.27,0.32,0.40,0.55,...,0.02,0.05,0.05,0.04,0.05,0.05,0.06,0.07,0.11,0.10
max,1.10,0.87,0.77,0.78,0.80,0.82,0.85,0.88,0.96,1.19,...,1.22,0.77,0.78,0.79,0.79,0.78,0.77,0.77,0.80,1.16

In [4]:
x.toDataFrame(Vars=Target).describe()

         Tau355    Tau440    Tau550    Tau870
count 119319.00 119319.00 119319.00 119319.00
mean       0.13      0.12      0.10      0.08
std        0.17      0.16      0.15      0.14
min        0.01      0.00      0.00      0.00
25%        0.05      0.04      0.04      0.03
50%        0.08      0.07      0.06      0.05
75%        0.14      0.12      0.11      0.09
max        5.93      5.52      5.55      5.55