# Exercising the BoxCox Transforms
This note exercises the BoxCox transform methods workinmg on Pandas DataFrames.

In [1]:
%load_ext autoreload
%autoreload 2

import sys
sys.path.append('..')

from obs.g5nr import G5NR_QC, Meta, Target, Features, pFeatures
import pandas as pd    

pd.set_option('display.float_format', lambda x: '%.2f' % x)

## Load G5NR Simulated Data

In [2]:
x = G5NR_QC(Dir='..')

### Angles
Notice that these are in degrees and that there is no limit placed on the glint angle.

In [55]:
features = x.toDataFrame(Vars=('GlintAngle', 'ScatteringAngle')+Features)
display(features.iloc[:,0:10].describe())
display(features.iloc[:,10:20].describe())

,GlintAngle.01,GlintAngle.02,GlintAngle.03,GlintAngle.04,GlintAngle.05,GlintAngle.06,GlintAngle.07,GlintAngle.08,GlintAngle.09,GlintAngle.10
count,119319.00,119319.00,119319.00,119319.00,119319.00,119319.00,119319.00,119319.00,119319.00,119319.00
mean,71.54,61.88,54.98,50.30,47.73,47.24,48.88,52.78,59.13,68.53
std,36.19,31.54,26.20,21.12,17.85,18.08,21.67,26.92,32.31,36.81
min,18.92,19.73,20.06,19.95,19.44,18.62,17.70,16.84,16.33,16.24
25%,36.28,33.08,32.96,32.49,31.81,31.09,30.44,30.02,29.95,32.39
50%,68.42,54.79,46.37,46.13,45.63,45.21,44.75,44.39,51.00,64.48
75%,103.62,89.36,76.23,63.63,62.43,62.13,62.15,74.22,86.97,100.85
max,140.15,125.96,112.51,99.32,86.29,86.35,99.27,112.37,125.70,139.70

,ScatteringAngle.01,ScatteringAngle.02,ScatteringAngle.03,ScatteringAngle.04,ScatteringAngle.05,ScatteringAngle.06,ScatteringAngle.07,ScatteringAngle.08,ScatteringAngle.09,ScatteringAngle.10
count,119319.00,119319.00,119319.00,119319.00,119319.00,119319.00,119319.00,119319.00,119319.00,119319.00
mean,111.43,120.78,127.12,131.04,132.74,132.30,129.77,125.16,118.33,108.70
std,36.75,32.22,26.86,21.64,18.06,17.88,21.16,26.21,31.54,36.18
min,40.47,54.42,67.69,80.71,93.67,93.70,80.69,67.59,54.23,40.11
25%,79.16,93.02,105.73,117.80,117.86,117.59,116.40,103.90,90.85,76.65
50%,115.50,128.92,135.51,135.17,134.75,134.38,133.94,133.74,125.47,111.90
75%,147.54,149.90,149.81,149.42,148.86,148.23,147.66,147.22,147.13,144.02
max,163.46,163.36,162.86,162.18,161.38,160.67,160.18,160.06,160.36,161.04

### TOA and Surface Reflectances

In [54]:
refl.iloc[:,24::10].describe() # just one if the angles

,Ref410.05,Ref550.05,Ref670.05,Ref870.05,Ref1550.05,Ref1650.05,Sre360.05,Sre380.05,Sre410.05,Sre550.05,Sre670.05,Sre870.05,Sre1550.05,Sre1650.05
count,119319.00,119319.00,119319.00,119319.00,119319.00,119319.00,119319.00,119319.00,119319.00,119319.00,119319.00,119319.00,119319.00,119319.00
mean,0.17,0.09,0.07,0.08,0.06,0.06,0.02,0.02,0.03,0.04,0.05,0.07,0.06,0.06
std,0.05,0.09,0.10,0.13,0.11,0.11,0.07,0.07,0.07,0.11,0.11,0.14,0.12,0.11
min,0.07,0.02,0.01,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
25%,0.14,0.05,0.03,0.01,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
50%,0.15,0.06,0.04,0.02,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01
75%,0.17,0.09,0.06,0.06,0.05,0.05,0.02,0.02,0.03,0.04,0.04,0.05,0.05,0.05
max,0.83,0.96,0.94,0.86,0.75,0.75,0.87,0.87,0.87,0.97,0.94,0.86,0.79,0.79

### Targets: AOD

In [42]:
target = x.toDataFrame(Vars=Target)
target.describe()

         Tau355    Tau440    Tau550    Tau870
count 119319.00 119319.00 119319.00 119319.00
mean       0.13      0.12      0.10      0.08
std        0.17      0.16      0.15      0.14
min        0.01      0.00      0.00      0.00
25%        0.05      0.04      0.04      0.03
50%        0.08      0.07      0.06      0.05
75%        0.14      0.12      0.11      0.09
max        5.93      5.52      5.55      5.55

## Apply Box-Cox Transform
Transform features and target

In [52]:
import boxcox

b = boxcox.Transform(features,target)
features_ = b.features
target_ = b.target

display(features.iloc[:,4::10].describe())
#features_.iloc[:,4::10].describe() # just one if the angles

/opt/anaconda3/lib/python3.9/site-packages/numpy/core/_methods.py:244: RuntimeWarning: overflow encountered in reduce
  ret = umr_sum(x, axis, dtype, out, keepdims=keepdims, where=where)
/opt/anaconda3/lib/python3.9/site-packages/numpy/core/_methods.py:233: RuntimeWarning: overflow encountered in multiply
  x = um.multiply(x, x, out=x)

,GlintAngle.05,Ref1550.05,Ref1650.05,Ref360.05,Ref380.05,Ref410.05,Ref550.05,Ref670.05,Ref870.05,ScatteringAngle.05,Sre1550.05,Sre1650.05,Sre360.05,Sre380.05,Sre410.05,Sre550.05,Sre670.05,Sre870.05
count,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,GlintAngle.05,Ref1550.05,Ref1650.05,Ref360.05,Ref380.05,Ref410.05,Ref550.05,Ref670.05,Ref870.05,ScatteringAngle.05,Sre1550.05,Sre1650.05,Sre360.05,Sre380.05,Sre410.05,Sre550.05,Sre670.05,Sre870.05
count,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Check BoxCox Transform

In [43]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
from scipy import stats

import misc.kde as kde

In [44]:
def plot_kde(tau,range=(-0.25,0.7),
             title='Aerosol Optical Depth KDE',
             xlabel=r'$\tau$',
             ylabel='Density'):
    """
    Plot KDE of log transform
    """
    x = tau

    # KDE
    bins, P = kde.calc_kde1d(x,range=range)

    # Calculate corresponding Gaussian distribution
    mu = np.mean(x)
    sig = np.std(x)
    G = 1. /(sig * np.sqrt(2 * np.pi)) * np.exp( - (bins - mu)**2 / (2 * sig**2) )
    
    # Plot KDE & Gaussian
    #plt.rcParams['figure.figsize'] = (800,600)
    plt.plot(bins,P,'b',label='KDE')
    plt.plot(bins,G,'r',label='Gaussian')
    #plt.plot(bins,G*np.log(G/P),'k',label='KL Integrand')
    plt.grid()
    plt.legend()
    plt.xlabel(xlabel)
    plt.ylabel(ylabel)
    plt.title(title)

### Select Features

In [47]:


plot_kde(features['Ref550.05'],range=(-3,3), xlabel='Reflectance',title='550 nm Reflectance, 5th Angle')

ValueError: array must not contain infs or NaNs